### ISSUE TITLE
Absolute path gets turned into bad relative path in Problems list

### ISSUE THREAD

**Issue by edbaskerville** [rust-lang/rls-vscode#280]
I have a project crate with a path dependency to another crate with the same parent directory, e.g.:

```toml
[dependencies]
mylib = { path = "../mylib" }
```

`cargo build` prints error lines with absolute paths that are correct, e.g.:

```
error[E0308]: mismatched types
  --> /Users/ed/project/mylib/src/mymod.rs:81:23
```

but the Problems view in VS Code turns it into a bad relative file URL, by appending all the absolute path components to the absolute path for the active crate. When I click on the error, it looks like:

```
Unable to open 'mymod.rs': File not found 
(file:///Users/ed/project/myapp/Users/ed/project/mylib/src/mymod.rs).
```

**Comment by Xanewok** [comment]
Can't reproduce with the following project layout:

root/inner1/src/lib.rs
```rust
pub fn inner1_fn(_arg: bool) -> bool { true }

fn inner1_inner() {
    inner1_fn(5);
}
```

root/inner2/src/main.rs
```rust
use std::path::Path;

fn main() {}
```

root/inner2/Cargo.toml
```toml
[package]
name = "inner2"
version = "0.1.0"
authors = ["example <example@example.com>"]
edition = "2018"

[dependencies]
inner1 = { path = "../inner1"}
```

root/Cargo.toml
```toml
[workspace]
members = [
    "inner1",
    "inner2"
]
```

The files in Problems pane are correct regardless of the relative "../inner1" path.
I'll close this but please reopen if that still persists and please include a simple reproduction so that I can take a look at this, thanks!
